<font size="6"> Introduction </font>  

<font size="4" style="color:blue;">Draft Picks as of Nov 14th, 2023 </font>

<p>Here it is guys! The complete draft order for the upcoming 2024 draft. Picks will be updated as they change</p>

In [13]:
import pandas as pd

In [14]:
vc2024 = pd.read_csv('https://raw.githubusercontent.com/blairjdaniel/blairjdaniel.github.io/main/2024.csv').style.set_properties(**{'text-align': 'left'})
vc2024

<font size="6"> Conditions are marked with a * beside the pick</font>

<font size="4" style="color:blue;"> September 11 </font>
<ul><li>Mat & Blair - if Bouchard or Bedard plays
less than 50 games, the other GM receives a 2nd (2024) for a 5th (2024) in return
If they both happen, the conditions cancel each other out.</li></ul>

<font size="4" style="color:blue;"> September 11 </font>
<ul><li>Kevin & Paul S - If Sanderson averages below 1.55 fppg, Kevin receives Paul's 5th(2024) rounder the following year in exchange for his lowest pick.</li></ul>

<font size="4" style="color:blue;"> September 18 </font>
<ul><li>Blair & Reed - If DeBrincat finishes season under 1.6 FTPs/Gm 1st (Moses' 2024) becomes 3rd (Moses' 2024)</li></ul>

<font size="4" style="color:blue;"> October 14 </font>
<ul><li>Reed & Paul S - The 5th(2024) with a clause that if Benson gets sent down before or after the 1st nine games it becomes a 7th(2024). But if he becomes a keeper for him this year, it becomes a 3rd(2024) regardless of any movement</li></ul>

<font size="4" style="color:blue;"> October 19 </font>
<ul><li>Geoff & Reed - If Ekblad hits 1.6 then Geoff gets Reed's 9th(2024) round pick and Reed gets Geoff's 3rd(2024). If Ekblad is under 1.6 then Reed gets Geoff's 5th(2024) and Geoff gets Reed's 10th(2024) .</li></ul>

<font size="4" style="color:blue;"> October 19 </font>
<ul><li>Jamie & Reed - Condition is a 3rd(2024) if Jamie keeps Knies</li></ul>

<font size="4" style="color:blue;">  </font>
<ul><li></li></ul>

In [15]:
vc2025 = pd.read_csv('https://raw.githubusercontent.com/blairjdaniel/blairjdaniel.github.io/main/2025.csv').style.set_properties(**{'text-align': 'left'})
vc2025